beclab/Installer

- cmd/ctl/os/download.go
the current `Errorf` only prints the error, but a zero exit code is still returned, resulting the `install.sh` to continue executing regardless of the error.
> fix: return non-zero exit code upon error

- .gitignore
- pkg/k3s/tasks.go
- pkg/k3s/templates/k3sService.go
- pkg/kubernetes/module.go
- pkg/kubernetes/templates/kubelet_service.go
- pkg/storage/constants.go
If for some reasons the rootfs of Terminus is not mounted by JuiceFS, for example if the Redis or MinIO service is down, or juiceFS inits with a config pointing to the wrong storage backend,
and the kubelet still starts and runs pods regardlessly,
the I/Os done by the pods are on the local FS of the host machine, instead of to JuiceFS,
which messes up app data, e.g. cookie sessions stored in Redis or data of Files will be lost
this case can be avoided by always checking the rootfs is mounted before starting kubelet, 
by simply add a `ExecStartPre=juicefs summary {rootfs mount path}` in the service file of k3s and kubelet
if the rootfs is not mounted, the command exits 1 and the starting of kubelet is retried by systems
> fix: do not start kubelet if juicefs is not mounted

- .goreleaser.yaml
- version/version.go
- inject latest git tag as version when building and releasing terminus-cli by adding the `-ldflags -X` option in the goreleaser config
- current 4 independent builds in the goreleaser config is merged to a unified one
- the build tags like `containers_image_openpgp` are for compiling some parts of KubeKey that are now unused, they are also removed
> feat: inject version at build time

- pkg/bootstrap/download/module.go
- pkg/bootstrap/patch/module.go
- pkg/core/connector/runtime.go
- pkg/core/logger/logger.go
- pkg/images/module.go
- pkg/terminus/account.go
tee the console installation log to the `.terminus/versions/v{VERSION}/logs/install.log` for backward compatibility and add more [INFO] and [FATAL] logs for cloud provisioning scenario
> fix: add backward logging compatibility for cloud provisioning

- pkg/bootstrap/precheck/tasks.go
- pkg/core/connector/system.go
- pkg/core/util/ip.go
- pkg/storage/redis.go
select local IP address by the following priority:
- env var `OS_LOCALIP`
- lookup hostname
- local network interface's address
only exit with error when no valid IP address can be found
> fix: support auto-selecting unspecified local interface IP

- pkg/bootstrap/registry/templates/harbor.go
- pkg/bootstrap/registry/templates/registry.go
- pkg/certs/templates/certs_renew_service.go
- pkg/container/templates/containerd_service.go
- pkg/container/templates/docker_service.go
- pkg/daemon/templates/terminusd_service.go
- pkg/etcd/templates/backup_service.go
- pkg/etcd/templates/etcd_service.go
- pkg/k3s/templates/k3sService.go
- pkg/kubernetes/templates/kubelet_service.go
- pkg/storage/templates/juicefs.go
- pkg/storage/templates/minio.go
- pkg/storage/templates/redis.go
As per the official doc of systemd: https://www.freedesktop.org/software/systemd/man/latest/systemd.unit.html#StartLimitIntervalSec=interval
> Configure unit start rate limiting. Units which are started more than burst times within an interval time span are **not permitted to start any more**. Use StartLimitIntervalSec= to configure the checking interval and StartLimitBurst= to configure how many starts per interval are allowed.
the current service unit files we create will stop retrying once they reach the burst limit, which is not an expected behaviour
> fix: lift the retry limit on all systemd units

- pkg/terminus/settings.go
- pkg/terminus/templates/settings.go
the legacy way of filling placeholder strings in yaml files (notably the `terminus_cr.yaml`) before installing it by helm may cause a problem that, if the OS is uninstalled and then installed again, the modified yaml files will remain the same and the replace operation in the new installation process will not take any effect, resulting in in consistent behaviors.
> fix: use helm templating instead of sed replace

- cmd/ctl/os/release.go
- cmd/ctl/os/root.go
- pkg/bootstrap/os/tasks.go
- pkg/core/util/file.go
- pkg/release/app/app.go
- pkg/release/builder/builder.go
- pkg/release/manifest/manifest.go
- pkg/terminus/tasks.go
- pkg/utils/file.go
add command `olares-cli olares release` to build a local release based on a local `Olares` repo.
basically, it's a port of [build.sh](https://github.com/beclab/Olares/blob/main/scripts/build.sh) and other relevant scripts in golang, only without the upload functions.
> feat: add command to build local release of Olares

- pkg/terminus/welcome.go
check key pods are running by namespace rather than labels when waiting for OS to boot up.
> fix: remove check for non-existing apps

- cmd/ctl/os/download.go
- cmd/ctl/os/install.go
- cmd/ctl/os/prepare.go
- cmd/ctl/os/uninstall.go
- pkg/pipelines/install_terminus.go
- pkg/pipelines/prepare_system.go
the  logger in the `"bytetrade.io/web3os/installer/pkg/core/logger"` package, used across this project, is initialized in:
https://github.com/beclab/Installer/blob/f801ceeb8ac7eae21cdd0744e1b6eb34e658028a/pkg/core/connector/runtime.go#L81
which is typically called in the `Run` method of a command like this:
https://github.com/beclab/Installer/blob/f801ceeb8ac7eae21cdd0744e1b6eb34e658028a/cmd/ctl/os/install.go#L26-L28
but other errors might also be returned *before* the logger is actually initialized, resulting in a nil pointer panic.
we should just simply use the logger from the standard library in this case, because:
- if the command errors out before the logger is initialized, it means no task has been executed, thus a simple console log is enough.
- if the command errors out after the …
> fix: use the logger from std lib at cmd entry

- .goreleaser.yaml
- pkg/common/kube_runtime.go
- pkg/core/util/ip.go
- pkg/core/util/util.go
- pkg/phase/cluster/changeip.go
- pkg/terminus/prepares.go
- pkg/terminus/settings.go
- pkg/terminus/tasks.go
- pkg/terminus/welcome.go
detect public IP when installing Olares by:
1. check whether the machine has a local network interface to which a public IP is bound
2. if the machine is an AWS EC2 instance, check whether it has an associated public IP address by contacting the IMDS service
if a public IP is detected, the `selfhosted` setting is turned off when installing related components.
> feat: detect public ip and adjust the setting of "selfhosted"

- .github/workflows/release.yaml
the latest is ubuntu-24.04, on which some jobs will fail to run.
> ci: use stable runner ubuntu-22.04 rather than latest

- pkg/bootstrap/precheck/module.go
cloud instance already has containerd installed and should not be blocked by the containerd conflicting precheck.
> fix: do not precheck containerd on cloud instance

- pkg/phase/cluster/linux.go
- pkg/windows/tasks.go
Install Olares in WSL, with GPU-related components installed by default, without relying on parameters set in environment variables.
> fix: ignore the value of Windows gpu env vars during wsl installation

- pkg/bootstrap/precheck/tasks.go
port 9100 in host network is required by the node exporter.
> fix: add precheck for port 9100

- go.mod
- go.sum
- pkg/common/common.go
- pkg/kubesphere/minikube.go
- pkg/phase/system/macos.go
change Minikube runtime to containerd, and modify the `/etc/containerd/config.toml` config file in Minikube to add registry mirrors, if the `--registry-mirrors` option is set at prepare phase.
> feat: support setting registry mirrors for minikube

- cmd/ctl/options/cli_options.go
- cmd/ctl/os/install.go
- cmd/ctl/os/storage.go
- pkg/common/common.go
- pkg/common/kube_runtime.go
- pkg/phase/cluster/delete_cluster.go
- pkg/phase/cluster/linux.go
- pkg/phase/cluster/utils.go
- pkg/phase/system/linux.go
- pkg/phase/system/storage.go
- pkg/phase/system/utils.go
- pkg/pipelines/install_terminus.go
- pkg/pipelines/prepare_system.go
- pkg/pipelines/storage.go
- pkg/storage/juicefs.go
- pkg/storage/module.go
- pkg/storage/tasks.go
- pkg/storage/validate.go
- tasks related to object storage installation are moved out of `prepare` phase into a separate `install storage` phase
- a MinIO instance managed by Olares will be installed as object storage service, if no external storage service is specified
- configs must be provided if external storage service is specified, this is validated in the `install storage` phase
- tasks and options related to JuiceFS and its dependency Redis are moved out of `prepare` phase into the `install` phase
- a `storage` phase between `install` and `prepare` is added into the `uninstall` command
> feat: seperate phase & command for storage installation

- pkg/kubesphere/minikube.go
If the `config_path` is set in the `[plugins."io.containerd.grpc.v1.cri".registry]` section in containerd config, the `[plugins."io.containerd.grpc.v1.cri".registry.mirrors]` will take no effect, so the `config_path` should be reset if we need to inject mirrors to the containerd config in MiniKube.
> fix: reset config path of cri plugin in minikube

- pkg/common/common.go
- pkg/windows/modules.go
- pkg/windows/tasks.go
install WSL to add the operation for setting firewall inbound rules.
- prompting the user whether to allow adding firewall rules to allow TCP protocol ports including 80, 443, and 30180. 
- If the Windows environment variable AUTO_ADD_FIREWALL_RULES is set to any value, the firewall rules will be automatically added.
> feat: add windows firewall rule

- pkg/core/util/ip.go
- pkg/terminus/settings.go
Some VPN services, e.g., tailscale, may set up a network device on the system which has a false public IP address.
The `PointToPoint` flag is set, and can be used to filter out such devices.
> fix: filter out p2p network interfaces when detecting machine IP

- pkg/gpu/tasks.go
- pkg/utils/gpu.go
- when the `nvidia-smi` command is installed but cuda driver is not installed, execution of `nvidia-smi` will result into an error, which should also be handled as a case of cuda driver not found.
- the current method of restarting the gpu plugins does not work.
> fix: handle the case where nvidia-smi is installed but no cuda driver

- pkg/common/common.go
- pkg/windows/tasks.go
when installing the WSL version of Olares, when prompted to enter the Domain Name, the default value set in the environment variable TERMINUS_OS_DOMAINNAME can be used.
> fix: set the TERMINUS_OS_DOMAINNAME environment

- pkg/bootstrap/precheck/module.go
- pkg/bootstrap/precheck/tasks.go
- pkg/common/common.go
- pkg/gpu/module.go
- pkg/gpu/tasks.go
the current `CudaCheckTask` has a field `SupportedCudaVersion` of type `[]string`, which is effectively a same list throughout the whole project, but has to be explicitly assigned a value, this assignment is likely to be missed by developers, we can just use a global variable to avoid such cases.
> fix: use global supported cuda version

- pkg/gpu/tasks.go
currently, only the systemd daemon is reloaded, but the script is not executed.
> fix: run cuda lib script in WSL before install plugin

- pkg/bootstrap/precheck/tasks.go
- pkg/gpu/prepares.go
- pkg/gpu/tasks.go
some native libs on Debian might be conflicting with a hard-coded version of Nvidia driver, so just let the package manager to decide a most appropriate version to install.
> fix: let package manager decide the version of nvidia driver

- pkg/bootstrap/precheck/module.go
- pkg/bootstrap/precheck/tasks.go
add the validity check of `/etc/resolv.conf` and `/run/systemd/resolve/resolv.conf` to the list of prechecks.
if the file specifies a search domain other than `.` or has a syntax error, fail the check.
> feat: check the validity of resolv.conf before installation

- pkg/bootstrap/patch/tasks.go
the previous test url of `https://download.docker.com/linux/ubuntu` cannot be reached by cn users, a url that's accessible by both cn and abroad users should be used to just check the normal functioning of the DNS server.
> fix: test DNS function properly

- pkg/windows/tasks.go
the environment variable added in the https://github.com/beclab/Installer/pull/116 should also be passed through from the Windows installer to the WSL installer.
> fix: pass the new env NVIDIA_CONTAINER_REPO_MIRROR from win to wsl

- pkg/container/containerd.go
the current way of installing containerd, when the olares-cli is executed under the `/` path, the `/bin` directory will be accidentally deleted.
> fix: extract containerd binary to /usr/bin directly

- pkg/phase/cluster/linux.go
- pkg/phase/cluster/macos.go
when the `WelcomeModule` is executed, it means all the components of the system have already been installed, we're only waiting for them to initialize, if the wait times out and the installer exits, chances are that the system may still be usable some time later, but the `InstalledModule` is not executed and the `.installed` phase file is not written, which some other tasks depend on, unexpected problems may occur.
therefore, the `InstalledModule` should be executed before the `WelcomeModule`, not after.
> fix: write install phase file before wait for system init

- pkg/bootstrap/patch/tasks.go
- pkg/common/common.go
If we need to alter the user's DNS server config during installation, first check if it's a CN user by match the registry mirrors against CN mirrors provided by Olares, and switch the secondary `114.114.114.114` DNS server with the primary `1.1.1.1` DNS server if true. This can help CN users to resolve to nearest CDN rather than the default one.
> fix: switch primary and secondary DNS server for CN user

- cmd/ctl/os/root.go
- cmd/ctl/os/startstop.go
- pkg/bootstrap/os/tasks.go
- pkg/container/containerd.go
- pkg/container/module.go
- pkg/core/prepare/delay.go
- pkg/kubernetes/tasks.go
- pkg/pipelines/startstop.go
- pkg/terminus/modules.go
- pkg/terminus/tasks.go
the following commands are added:
- `olares-cli olares stop` to stop components of an installed (or partially installed) Olares.
- `olares-cli olares start` to start components of an installed (or partially installed) and already stopped Olares, and wait for all system pods to be running again.
> feat: add commands to start/stop Olares components

- apis/kubekey/v1alpha2/default.go
- apis/kubekey/v1alpha2/kubernetes_types.go
- pkg/k3s/tasks.go
- pkg/k3s/templates/k3sService.go
- pkg/kubernetes/templates/v1beta2/kubeadm_config.go
add a default `shutdownGracePeriod` of `30s` and `shutdownGracePeriodCriticalPods` of `10s` to kubelet config, to enable the node graceful shutdown feature of Kubernetes, and make the shutdown process quicker.
> feat: add node graceful shutdown conf

- pkg/k3s/tasks.go
- pkg/kubernetes/templates/v1beta2/kubeadm_config.go
set the `terminaged-pod-gc-threshold` option of kube-controller-manager to 1 to trigger automatical garbage collection of terminated pods.
note that the smallest valid value for this option is `1`, so in some cases a terminated pod will still be left not cleaned, the complete garbage collection of terminated pod is discussed in the Kubernetes repo but not merged: https://github.com/kubernetes/enhancements/issues/2890, so maybe in the future we should add a garbage collection controller that cleans up all terminated pods if necessary.
> feat: lower pod gc threshold

- cmd/ctl/os/logs.go
- cmd/ctl/os/root.go
a new command `olares-cli olares logs` is added to collect various components of Olares, with the following optional flags:
- --components, specific components (systemd service) to collect logs from (comma-separated). If empty, collects from all the default components that can be found: `k3s, containerd, olaresd, kubelet, juicefs, redis, minio, etcd, NetworkManager`.
- --ignore-kube-errors, whether to exit with error or to continue with a warning if the Kubernetes api server can not be reached to fetch cluster infos, defaults to `false`
- --max-lines, limit the maximum lines of every component's logs, to avoid a log file that's too large, defaults to `3000`
- --since, only fetch logs newer than a relative duration like 5s, 2m, or 3h, defaults to `7d`
- --output-dir, directory to store …
> feat: add command to collect logs

- pkg/plugins/dns/module.go
the env `COREDNS_SVC` is set to the service ip of coredns
> feat: inject coredns service ip to global envs

- apis/kubekey/v1alpha2/cluster_types.go
- pkg/plugins/dns/module.go
the `ClusterIP()` is not used anymore and should be removed to avoid ambiguity
> fix: pass the correct coredns service ip

- pkg/common/common.go
the app-service needs this value to configure the settings for newly created users.
> fix: add MARKET_PROVIDER to global envs

- pkg/bootstrap/os/tasks.go
- pkg/bootstrap/patch/tasks.go
- pkg/common/common.go
- pkg/phase/cluster/delete_cluster.go
Multiple reinstallation of Kubernetes might introduce some conflicts, especially across different versions.
In this specific case, the ipset sets and ip6tables rules managed by a v1.32 kube-proxy instance were left not cleaned even after a total uninstallation, and the ipset sets with a new revision has resulted in the calico of an older version refusing to start.
Two simple commands are added in this PR to clear these data during installation.
Note that a ipset set referenced by any iptables rules can only be deleted after the rules are gone.
> fix: clear ip6tables and ipset data during uninstall

- go.mod
- go.sum
- pkg/common/common.go
- pkg/common/kube_runtime.go
- pkg/core/connector/runtime.go
- pkg/daemon/task.go
- pkg/phase/cluster/delete_cluster.go
- pkg/phase/download/download_wizard.go
- pkg/phase/root.go
- pkg/phase/system/linux.go
- pkg/phase/system/wsl.go
- pkg/pipelines/add_node.go
- pkg/pipelines/changeip.go
- pkg/pipelines/check_download.go
- pkg/pipelines/download_package.go
- pkg/pipelines/download_wizard.go
- pkg/pipelines/gpu_install.go
- pkg/pipelines/info_terminus.go
- pkg/pipelines/install_terminus.go
- pkg/pipelines/precheck.go
- pkg/pipelines/prepare_system.go
- pkg/pipelines/storage.go
- pkg/pipelines/uninstall_terminus.go
- pkg/terminus/modules.go
- pkg/terminus/tasks.go
- pkg/windows/tasks.go
Save the metadata value of `basedir` and `version` in the `/etc/olares/release` file with a dot env format, like the `/etc/os-release` file, e.g.:
```
~ cat /etc/olares/release
OLARES_BASE_DIR="/home/keven/.olares"
OLARES_VERSION="1.12.0-20250408"
```
And the config is loaded from the following sources, with each source overriding the previous:
- /etc/olares/release
- environment variables, i.e., `OLARES_BASE_DIR`, `OLARES_VERSION` 
- command line options, i.e., `--base-dir/-b`, `--version/-v`
In the absence of the release file, or when the command line options are explicitly specified, the current behavior is retained.
The release file is saved when the `prepare` phase is finished, thus enabling multiple execution of`olares-cli olares uninstall` and `olares-cli olares install` without …
> feat: save metadata to and read from release file

- go.mod
- go.sum
**Background**
- fix the backups-sdk log initialization process, so that the logging component is only initialized when executing backup-related commands. 
- read the log file storage path from /etc/olares/release
**PRs**：
https://github.com/Above-Os/backups-sdk/pull/14
> fix: backups-sdk read base-dir from release file

- go.mod
- go.sum
**Background**
- fix: callback function blocking
- fix: terminal execution with -v flag error
- fix: add backup traceId
**PRs**
https://github.com/Above-Os/backups-sdk/pull/18
> fix: backups-sdk up to 0.1.12

- go.mod
- go.sum
**Background**
fix traceId is nil, add error message output when using cli for backup and restore
**PRs**
https://github.com/Above-Os/backups-sdk/pull/19
https://github.com/Above-Os/backups-sdk/commit/c10ce08025932592aca0f90bb51fa718e4acd601
> fix: backups-sdk up to 0.1.14

- cmd/ctl/gpu/root.go
- cmd/ctl/gpu/upgrade.go
- pkg/bootstrap/precheck/tasks.go
- pkg/gpu/module.go
- pkg/gpu/tasks.go
- pkg/pipelines/gpu_upgrade.go
- pkg/terminus/tasks.go
- Change the default GPU driver during installation to 570 (CUDA version: 12.8)
- Add a new command `olares-cli gpu upgrade` to upgrade an older GPU driver to the current version.
> feat: add command to upgrade GPU driver

- pkg/kubesphere/plugins/kscore.go
- pkg/kubesphere/plugins/kscore_config.go
- pkg/kubesphere/plugins/monitor_notification.go
- pkg/kubesphere/plugins/redis.go
- pkg/kubesphere/plugins/snapshotcontroller.go
Change all the current installation of charts from `Install` to `Upgrade` to make them idempotent.
> feat: make installation idempotent using helm upgrade

- go.mod
- go.sum
**Background**
the backup path name is prefixed uniformly with "olares-backup/"
**PRs**
https://github.com/Above-Os/backups-sdk/pull/21
> fix: backups-sdk up to 0.1.16

- go.mod
- go.sum
**Background**
Supports backing up from a list file, using --files-from to select the files to back up.
**PRs**
https://github.com/Above-Os/backups-sdk/pull/22
> fix: backups-sdk up to 0.1.17

- cmd/ctl/options/gpu_options.go
- pkg/bootstrap/precheck/tasks.go
- pkg/common/common.go
- pkg/gpu/module.go
- pkg/gpu/prepares.go
- pkg/gpu/tasks.go
- pkg/phase/system/linux.go
- pkg/phase/system/wsl.go
- pkg/pipelines/gpu_install.go
- pkg/pipelines/gpu_upgrade.go
- upgrade CUDA to 12.9 (toolkit driver version 575)
- if the environment already has CUDA installed, the only version we tolerate is 12.9, rather than the current wide range
- during normal installation, if GPU card is found, after installing the Nvidia driver, its running status is checked by executing `nvidia-smi`, if it's not running properly, the installation process will exit in failure, instead of the current behavior of skipping other jobs silently
- during manually invoked GPU driver installation, i.e., `olares-cli gpu install/upgrade`, if no GPU card is found, the process will exit in failure. and if GPU card is found, `olares-cli gpu install` behaves like normal installation, while `olares-cli gpu upgrade` will proceed regardless of the status of the GPU driver, because …
> feat: upgrade cuda version and optimize gpu driver install logic
