cmd/ctl/options/cli_options.go
cmd/ctl/os/changeip.go
cmd/ctl/os/root.go
pkg/bootstrap/os/module.go
pkg/bootstrap/os/tasks.go
pkg/common/common.go
pkg/common/kube_runtime.go
pkg/common/local_runtime.go
pkg/core/connector/runtime.go
pkg/core/logger/logger.go
pkg/core/util/file.go
pkg/kubernetes/tasks.go
pkg/kubesphere/minikube.go
pkg/kubesphere/tasks.go
pkg/phase/cluster/changeip.go
pkg/phase/cluster/delete_cluster.go
pkg/phase/cluster/linux.go
pkg/phase/cluster/macos.go
pkg/pipelines/changeip.go
pkg/pipelines/uninstall_terminus.go
pkg/storage/juicefs.go
pkg/storage/minio.go
pkg/storage/redis.go
pkg/terminus/modules.go
pkg/terminus/natgateway.go
pkg/terminus/settings.go
pkg/terminus/tasks.go
pkg/terminus/templates/kk_hosts.go

usage: `sudo terminus-cli terminus change-ip --base-dir ~/.terminus --version 1.10.0-20241103`
the IP set in the environment variable `OS_LOCALIP` or in the /etc/hosts file is given priority, if neither of them is set or it's set but unboundable by any local network interface, a local interface IP address is chosen.

feat: add change ip command

---

.github/workflows/release.yaml

- remove unnecessary steps and inputs
- automatic run on tag push
- fetch tags for goreleaser version injection

feat: tidy and add some new configs in github action

---

apis/kubekey/v1alpha2/default.go
pkg/bootstrap/precheck/tasks.go
pkg/common/common.go
pkg/files/file.go
pkg/files/file_url.go
pkg/phase/cluster/delete_cluster.go
pkg/pipelines/prepare_system.go
pkg/storage/juicefs.go
pkg/storage/module.go
pkg/storage/prepares.go
pkg/storage/tasks.go

feat: support for tencent cloud COS

feat: support tencent cloud storage

---

pkg/gpu/tasks.go
pkg/phase/cluster/linux.go
pkg/phase/cluster/utils.go

fix: Install wsl without gpu, exclude the installation of nvidia device plugins

fix: Install wsl without a gpu

---

pkg/kubesphere/tasks.go

it takes some time before the kube-proxy ensures the IPVS rule is applied, after the ks-controller-manager pod is up and running.

fix: check the connectivity of ks-controller svc

---

pkg/kubesphere/tasks.go

Don't check the connectivity of KS service on the macOS cuz it can't be reached from the host machine.

fix: do not check ks svc connectivity on macOS

---

pkg/terminus/natgateway.go

Get a valid IP address from the local network interfaces of MacOS, and use it as the default IP of NAT gateway, saves the hassle of typing the IP manually if it is the IP address they want.
```
2024-11-28T17:47:32.276+0800	[Module] GetNATGatewayIP
Enter the NAT gateway(the MacOS host)'s IP [default: 192.168.1.5]:
2024-11-28T17:56:31.627+0800	Nat Gateway IP: 192.168.1.5
2024-11-28T17:56:31.632+0800	[A] LocalHost: GetNATGatewayIP success (8m59.36280975s)
```

feat: set default nat gateway ip in prompt for mac

---

pkg/core/util/ip.go

prioritize the IP address of the network interface connected to the global default gateway in every local IP pick-up scenarios, rather than as a fallback.
this prevents the case where a local hostname resolves to multiple IPs and the first indexed IP is not what we want.

fix: pioritize default route ip in all scenarios

---

pkg/common/loader.go

cherry-pick of https://github.com/beclab/Installer/pull/70 on `release-0.1.74`

cherry-pick of #70: fix: install sudo if it's missing

---

cmd/ctl/os/download.go
cmd/ctl/os/install.go
cmd/ctl/os/prepare.go
cmd/ctl/os/uninstall.go
pkg/pipelines/install_terminus.go
pkg/pipelines/prepare_system.go

cherry pick of https://github.com/beclab/Installer/pull/67 on release-0.1.74

cherry pick of #67: fix: use the logger from std lib at cmd entry

---

pkg/bootstrap/precheck/module.go
pkg/bootstrap/precheck/tasks.go

when installing in a PVE environment, the status of apt-get update will be checked.

fix: check the status of apt-get update for PVE

---

pkg/kubesphere/minikube.go

When MiniKube starts an existing profile, it first checks whether a list of essential k8s images are already loaded, if not, a pre downloaded tarball containing the images is extracted into the profile:
https://github.com/kubernetes/minikube/blob/3dae3866bd4370c0f3bef22ace0071f9f83f6193/pkg/minikube/cruntime/containerd.go#L567
The tarball, e.g., `.minikube/cache/preloaded-tarball/preloaded-images-k8s-v18-v1.22.10-containerd-overlay2-arm64.tar.lz4`, is an archive of `/var/lib/containerd` directory containing containerd metadata and blob layers, and once extracted, will overwrite the image metadata in `/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/metadata.db`, thus all other images loaded into the profile are gone, even though their blob layers are still left intact.
Normally …

fix: tag k8s images in minikube to avoid destructive reload

---

cmd/ctl/options/cli_options.go
cmd/ctl/os/precheck.go
cmd/ctl/os/root.go
pkg/bootstrap/os/module.go
pkg/bootstrap/os/tasks.go
pkg/bootstrap/patch/module.go
pkg/bootstrap/patch/tasks.go
pkg/bootstrap/precheck/module.go
pkg/bootstrap/precheck/tasks.go
pkg/core/connector/system.go
pkg/phase/system/linux.go
pkg/phase/system/wsl.go
pkg/pipelines/precheck.go

add a separate command for precheck, which runs the defined checks and prints out all problems.
some tasks that are not supposed to be put in the precheck module are moved out to other appropriate modules.

feat: add separate command for precheck

---

apis/kubekey/v1alpha2/default.go
pkg/gpu/tasks.go
pkg/phase/system/utils.go

install the `nvidia-open-560` package on Debian, and unify the `libnvidia-container.list` repo for Debian and Ubuntu

feat: support enabling GPU on Debian & Ubuntu24

---

go.mod
pkg/common/common.go
pkg/core/common/common.go
pkg/phase/cluster/windows.go
pkg/utils/cmd.go
pkg/utils/disk_darwin.go
pkg/utils/disk_linux.go
pkg/utils/disk_windows.go
pkg/utils/encoding.go
pkg/windows/modules.go
pkg/windows/tasks.go

feat: allow selecting the storage location for WSL Ubuntu Distro during installation to avoid excessive space usage on the C drive

feat: set Distro storage location

---

pkg/core/connector/ssh.go

the current SSH connection implementation catches the interactive prompt of `sudo` and inputs the corresponding host's password, but only checks for the default English prompt, the catch can miss in other cases where the system has a different sudo prompt, e.g., specified by either the security policy or the SUDO_PROMPT environment variable, or the locale is of another language, like https://github.com/sudo-project/sudo/blob/a3cd820d21ea9d6db2ddbd7ff95e96a88f810b8b/plugins/sudoers/po/zh_CN.po#L32
an explicit prompt override is specified by `sudo -p` when executing the command, to make the prompt catch more robust, and the unique case where the prompt has a Chinese colon is also watched.

fix: more robust way to catch sudo prompt

---

pkg/k3s/tasks.go
pkg/kubernetes/templates/v1beta2/kubeadm_config.go

this is a cherry pick of https://github.com/beclab/Installer/pull/143

fix: raise cri timeout to accommodate slow hardwares (#143)

---

pkg/common/common.go

to enable app-service to download packages from a proper source when upgrading system

feat: pass cdn url env to app-service

---

pkg/common/common.go

this is a cherry pick of https://github.com/beclab/Installer/pull/153

feat: pass cdn url env to app-service (#153)

---

pkg/common/loader.go

redundant trailing slashes in a registry mirror url, like `https://a.b/` or `https://a.b//`, will result in the containerd not adding a `/v2` in the url path when resolving and fetching images: https://github.com/containerd/containerd/blob/11b1353c12b9f3a1542ffe44a00a988e330f8c56/internal/cri/server/images/image_pull.go#L484-L486
and causes failure to pull image.

fix: trim all redundant slashes in the mirror url

---

pkg/common/loader.go

this is a cherry pick of https://github.com/beclab/Installer/pull/158

fix: trim all redundant slashes in the mirror url (#158)

---

pkg/kubesphere/plugins/files/build/ks-core-config/values.yaml
pkg/kubesphere/plugins/files/build/ks-core/values.yaml

fix: ks-apiserver change handle node shell to bash

fix: ks-apiserver change handle node shell to bash

---

pkg/bootstrap/patch/tasks.go
pkg/common/common.go

this is a cherry-pick of https://github.com/beclab/Installer/pull/169

fix: switch primary and secondary DNS server for CN user

---

go.mod
go.sum

backups-sdk update, add terminal command for querying regions

fix: import RegionsCommand from backups-sdk

---

cmd/ctl/os/root.go
cmd/ctl/os/startstop.go
pkg/bootstrap/os/tasks.go
pkg/container/containerd.go
pkg/container/module.go
pkg/core/prepare/delay.go
pkg/kubernetes/tasks.go
pkg/pipelines/startstop.go
pkg/terminus/modules.go
pkg/terminus/tasks.go

this is a cherry-pick of https://github.com/beclab/Installer/pull/172

feat: add commands to start/stop Olares components (#172)

---

cmd/ctl/os/logs.go
cmd/ctl/os/root.go

this is a cherry-pick of https://github.com/beclab/Installer/pull/174

feat: add command to collect logs (#174)

---

pkg/common/common.go

this is a cherry pick of https://github.com/beclab/Installer/pull/189

fix: add MARKET_PROVIDER to global envs

---

go.mod
go.sum

https://github.com/Above-Os/backups-sdk/commit/3246e815b9de919985d255a3534aafbf4628162a

fix: restore path not specified

---

go.mod
go.sum
pkg/common/common.go
pkg/common/kube_runtime.go
pkg/core/connector/runtime.go
pkg/daemon/task.go
pkg/phase/cluster/delete_cluster.go
pkg/phase/download/download_wizard.go
pkg/phase/root.go
pkg/phase/system/linux.go
pkg/phase/system/wsl.go
pkg/pipelines/add_node.go
pkg/pipelines/changeip.go
pkg/pipelines/check_download.go
pkg/pipelines/download_package.go
pkg/pipelines/download_wizard.go
pkg/pipelines/gpu_install.go
pkg/pipelines/info_terminus.go
pkg/pipelines/install_terminus.go
pkg/pipelines/precheck.go
pkg/pipelines/prepare_system.go
pkg/pipelines/storage.go
pkg/pipelines/uninstall_terminus.go
pkg/terminus/modules.go
pkg/terminus/tasks.go
pkg/windows/tasks.go

this is a cherry pick of https://github.com/beclab/Installer/pull/193

feat: save metadata to and read from release file (#193)

---

cmd/ctl/os/logs.go

collect more logs such as the olares-cli logs and system network configs

feat: collect more logs

---

pkg/core/util/ip.go

In EC2 instances with newer kernels, IMDS v2 is forced and a token is needed to request the IMDS service.

fix: request IMDSv2 service with token

---

go.mod
go.sum

fix: backups-sdk up to 0.1.17
